config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  devise_for :users
  root to: "posts#index"

  resources :posts do
    resources :likes
    resources :comments do 
      resources :comments
    end

    get'profile', to: 'posts#profile', on: :collection
  end

  #  resources :comments do
  #   resources :comments
  # end
  
  delete '/posts/:id', to: 'posts#destroy', as: 'delete_post'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :post
    belongs_to :user
    has_many :comments, class_name: 'Comment', foreign_key: "parent_id"
    belongs_to :parent, class_name: 'Comment', optional: true
end

app/models/concerns/searchable.rb
# module Searchable
#   extend ActiveSupport::Concern
# byebug
#   included do
#     include Elasticsearch::Model
#     include Elasticsearch::Model::Callbacks

#     # mapping do
#     #     indexes :name, type: :text
#     #     indexes :image, type: :string
#     #     indexes :comment, type: :text
#     # end

#         def self.search(query)
#           params = {
#             query: {
#               multi_match: {
#                 query: query, 
#                 fields: [ :name, :image, :comment ] 
#               },
#             },
#           }

#           self.__elasticsearch__.search(params)
#         # end
        
#     end
#   end
# end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord	
	belongs_to :user
    has_many :comments, dependent: :destroy 
	has_many :likes, dependent: :destroy
   	# has_many_attached :images
	has_one_attached :image

	validates :name, presence: true
	validates :image, presence: true


	def self.search(search)
	  Post.where("name LIKE ?", "%#{search}%") 
	  Post.joins(:comments).where('comments.Comment LIKE ?', "%#{search}%" )
	end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :likes, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!		

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	# def index
	# 	@comment = Comment.all
	# end

	# def show
	# 	@comment = @post.comments.create(comment_params)
	# end

	# def new
	# 	@comment = Comment.new
	# end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id
		@comment.save!
		 redirect_to posts_path(@post)
	end



# 	def create
# byebug		
#   @comment = Comment.new(comment_params)
#   @comment.post = Post.find(params[:post_id])

#   if params[:comment_id]
#     @comment.parent_comment = Comment.find(params[:comment_id])
#   end

#   if @comment.save
#     redirect_to post_path(@comment.post)
#   else
#     render :new
#   end
# end




# 	def new
# byebug		
# 	  @comment = Comment.new(parent_id: params[:parent_id])
# 	end

# 	def create
# 	  if params[:comment][:parent_id].to_i > 0
# 	    parent = Comment.find_by_id(params[:comment].delete(:parent_id))
# 	    @comment = parent.children.build(comment_params)
# 	     @comment.save
# 	  else
# 	    @comment = Comment.new(comment_params)
# 	  	 @comment.save
# 	  end
# 	end


# 	def reply
# byebug		
# 		if params[:comment][:parent_id].present?
# 		    parent = Comment.where(params[:comment][:parent_id]).first
# 		    comment = parent.post.build(comment_params)
# 		  else
# 		    comment = Comment.new(comment_params)
# 		    if comment.save
# 		       	redirect_to post_comments_comment_path(@post)
# 		    else
# 		     render json: {success: false, message: "Something went wrong"}
# 		    end
# 		 end
# 	end

	# def destroy
    #   @post = Post.find(params[:post_id])
    #   @comment = @post.comments.find(params[:id])
    #   @comment.destroy
    #   redirect_to post_path(@post)
 	# end

private

 	def comment_params
 		params.require(:comment).permit(:comment, :user_id, :post_id, :parent_id)
 	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
	before_action :find_like, only: [:destroy]


	def create
		  if already_liked?
		    flash[:notice] = "You can't like more than once"
		  else
		    @post.likes.create(user_id: current_user.id)
		  end
	redirect_to posts_path(@post)
	end

	def destroy
	  if !(already_liked?)
	    flash[:notice] = "Cannot unlike"
	  else
	    @like.destroy
	  end
	  redirect_to posts_path(@post)
	end

private
	
	def find_post
		@post = Post.find(params[:post_id])
	end

	def find_like
	   @like = @post.likes.find(params[:id])
	end

	def already_liked?
	  Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# before_action :authenticate_user!

before_action :data_find, only: [:show, :edit, :update, :destroy] 




   # def index
   #  # Searchkick.multi_search([Post, Comment], "query")

   #  search = params[:search].present? ? params[:search] : nil
   #    @posts = if search
   #      Post.where("name LIKE ? OR image LIKE ?","%#{search}%","%#{search}%")
   #    else
   #    # @posts = Post.search(params[:search],fields: ["name", "image"])
   #    @posts = Post.all.order("created_at DESC")
   #    end


  def index
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC") 
    else
      @posts = Post.all.order("created_at DESC")
    end
  end

  def profile
    @posts = Post.where(:user_id => current_user.id).order("created_at DESC")
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
   @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end 
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post successfully deleted"
    redirect_to posts_path, status: :see_other
  end


  private

  def data_find
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :image)   
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
  <h4>show parent comment:</h4>
  <%# @post.comments.each do |comment| %>
    <p>
      <strong><%= comment.user.email %></strong><br>
      <%= comment.comment %>
      <hr>
    </p>
  <%# end %>

app/views/comments/_form.html.erb
<h4>Post comment:</h4>
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.text_field :comment %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/show.html.erb
<p>
<strong><%= @comment.user.email %></strong><br>
<%= @comment.comment %><hr>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AzharSirPro</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script> -->

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-lg-top" id="cracker1-button">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Facebook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/posts/new">New Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/posts/profile">Profile</a>
        </li>
      </ul>
      <form class="d-flex">
        <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> -->
        <%= form_tag(posts_path, :method => "get") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Posts"%>&nbsp
          <%= submit_tag "Search" %>
        <% end %>
        <!-- <button class="btn btn-outline-success" type="submit">Search</button> -->
      </form>
    </div>
  </div>
</nav>
  


<!-- <%#= form_tag(posts_path, :method => "get") do %>
  <div class="input-group">
    <#%= search_field_tag :search, params[:search], placeholder: "Type", class: "form-control" %>
    <div class="input-group-btn">
      <%#= button_tag "Search for Post", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
    </div>
  </div>
<%# end %> -->


<div class="container">
  <div class="row">
    <div class="col-sm-9 bg-light p-3 border" id="all-data">
      <div style="margin-left:80px;">
        <%= yield %>
      </div>
    </div>
  </div>
</div>   

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
<div>
	<%= form.label :name %>
	<%= form.text_field :name %>
	<% @post.errors.full_messages_for(:name).each do |message| %>
		<div><%=message%></div>
	<%end%>
</div>	
<br>
<div>
	<%= form.label :image%>
	<%= form.file_field  :image, accept: 'image/png, image/gif, image/jpeg'%>
	<% @post.errors.full_messages_for(:image).each do |message| %>
		<div><%= message %></div>
	<%end%>
</div>
<br>
<div class="form-group mt-4 mb-5" id="cracker1-button">
	<%= form.submit class: "btn btn-primary btn-lg" %>
</div>
<%end%>


<!-- 
<%#= form_with model: @post, local: false do |form| %>
  <div class="modal-body">
	    <div>
			<%#= form.label :name %>
			<%#= form.text_field :name %>
			<%#@post.errors.full_messages_for(:name).each do |message| %>
				<div><%#=message%></div>
			<%#end%>
		</div>	
		<br>
		<div>
			<%#= form.label :image%>
			<%#= form.text_field :image %>
			<%# @post.errors.full_messages_for(:image).each do |message| %>
				<div><%#= message %></div>
			<%#end%>
		</div>
		<br>
  </div>
  <div class="modal-footer">
	    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	  	<%#= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<%#end%> -->

app/views/posts/_nes_comment_form.html.erb
<h4>Add a comment:</h4>
<%# @post = Post.last %>
<%= form_with model: [ post, post.comments.build ] do |form| %>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_field :comment %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/destroy.js.erb
// $('.delete_itemm').bind('ajax:success', function() {   
//    $(this).closest('tr').fadeOut();   
// });   

app/views/posts/edit.html.erb
<h1>Edit pages</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<!-- <h1>Posts index pages</h1>
<br>
<div id="cracker1-button">
	<%#= link_to "New Post", new_post_path, class: "btn btn-info btn-lg mb-3"%>
	<%#= link_to "profile" ,profile_posts_path, class: "btn btn-info btn-lg mb-3" %>
</div>
	<table>
		<thead class="table table-bordered"> 
			<th>id</th>
			<th>Name</th>
		</thead>

		<tbody class="table table-bordered">
			<%# @posts.each do |post| %>
			<tr>
				<td><%#= link_to "show", post_path(post), class: "btn btn-info"%></td>
		    <td id="cracker1-button"><%#= link_to "Edit", edit_post_path(post), method: 'get', class: "btn btn-info"%></td>
	      <td id="cracker1-button"><p><%#= post.likes.count %> <%#= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p></td>
			</tr>
			<%# end %>
      
      <td id="cracker1-button"><%#= link_to 'Like', post_likes_path(@post), method: :post, class: "btn btn-outline-primary" %></td> 

		</tbody>
	</table>
 -->
<!-- 
<br>
<%#= link_to "New Post", new_post_path, class: "btn btn-info btn-lg mb-3", data: { bs_toggle: 'modal', bs_target: '#newPostModal', remote: true } %>
<br><br>
<div class="modal fade" id="newPostModal" tabindex="-1" aria-labelledby="newPostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newPostModalLabel">Create New Post</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="newPostForm">

      </div>
    </div>
  </div>
</div> -->




	<table>
		<tbody>
			<% @posts.each do |post| %>
			<tr>
				<span><%#= link_to post.id, post %></span> 
				<span><h3><%=  post.name %></h3></span>
				<span><%= image_tag post.image,:size => "1100x600" if post.image.attached?%></span><br><br>

				<div>
					<% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
	        <% if pre_like %>
	          <span id="cracker1-button"><%= link_to 'Unlike', post_like_path(post, pre_like), method: :delete, class: "btn btn-outline-primary" %></span>
	        <% else %>
	            <span id="cracker1-button"><%= link_to 'Like', post_likes_path(post), method: :post, class: "btn btn-outline-primary" %></span>
	        <% end %>   

	        <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
	        &nbsp
	      	<!-- <span id="cracker1-button"><em><%#= post.likes.count %> <%#= (post.likes.count) == 1 ? 'Like' : 'Likes'%></em></span>&nbsp&nbsp -->
			    <span class="index-btn">
				    <span id="cracker1-button"><%= link_to "show", post_path(post), class: "btn btn-info"%></span>&nbsp&nbsp
				    <span id="cracker1-button"><%= link_to "Edit", edit_post_path(post), method: 'get', class: "btn btn-info"%></span>
		    	</span>
		    </div>
			</tr>
			
			<div class="comment-count">
					<h4>Comments <span class="tag is-rounded"><%= post.comments.count %> comments</span></h4>
      </div>

      	<strong> parent comment:</strong>
				<% post.comments.where(parent_id: nil).reverse.each do |c| %>
				  <p>
				    <strong><%= c.user.email %></strong><br>
				    <%= c.comment %>
				    <hr>

			    					<div id="nested_cmd">
							    		<strong>show child comment:</strong><br>
										  <% c.comments.where(parent_id: c.id).reverse.each do |c| %>
										    <strong><%= c.user.email %></strong>
										    <%= c.comment %><br>
											<% end %>


												<!-- <button class="showbtn btn btn-primary">Show Form</button> <button class="hidebtn btn btn-primary">Hide Form</button>
									      <p id="showhideForm" action="" method="post"> -->
												<%= form_with model: [ post, c, c.comments.build ] do |form| %>
												  <div >
														<%= form.hidden_field :parent_id, value: c.id %>
												    <%= form.text_field :comment %>
												  </div>
												   <div>
												    <%= form.submit %>
												  </div>
													<% end %>
												</p> 

												<!-- <script>
													$(document).ready(function(){
														$('.showbtn').click(function(){
													  		$('#showhideForm').show(500);
													  	});
													    $('.hidebtn').click(function(){
													  		$('#showhideForm').hide(500);
													  	});
													});
													</script> -->
							</div>
				  </p>
				<% end %>


				<h4>Post comment:</h4>
				<%= form_with model: [ post, post.comments.build ] do |form| %>
				  <p>
				    <%= form.text_field :comment %>
				  </p>

				  <p>
				    <%= form.submit %>
				  </p>
				<% end %>
			<br><br><br>
			<% end %>

		</tbody>
	</table>


</style>

app/views/posts/new.html.erb
<h1>Posts new pages</h1>
<%= render "form" %>

app/views/posts/new.js.erb
// $("#newPostForm").html("<%= escape_javascript render('form', post: @post)%>");

app/views/posts/profile.html.erb
<!-- <div id="cracker1-button"><%#= link_to "Back", posts_path, class: "btn btn-info"%></div> -->

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<button style="margin-left: 744px;">
 <% if user_signed_in? %>
   Logged in as <strong><%= current_user.email %></strong>
 <span id="cracker1-button"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link', class: "btn btn-warning" %></span>
 <span id="cracker1-button"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link', class: "btn btn-danger" %></span>
 <% else %>
  <%= link_to 'Edit Profile', edit_user_registration_path %>
   <span id="cracker1-button"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' , class: "btn btn-info"  %></span>
   <span id="cracker1-button"><%= link_to "Login", new_user_session_path, :class => 'navbar-link' , class: "btn btn-info"  %></span>
 <% end %>
</button>
<br><br>



<table>
	<tbody class="table table-bordered">
		<% @posts.each do |post| %>
			<tr>
				<span><%#= link_to post.id, post %></span> 
				<span><h3><%=  post.name %></h3></span>
				<span><%= image_tag post.image,:size => "1100x600" if post.image.attached?%></span><br><br>

				<div>
					<% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
	        <% if pre_like %>
	          <span id="cracker1-button"><%= link_to 'Unlike', post_like_path(post, pre_like), method: :delete, class: "btn btn-outline-primary" %></span>
	        <% else %>
	            <span id="cracker1-button"><%= link_to 'Like', post_likes_path(post), method: :post, class: "btn btn-outline-primary" %></span>
	        <% end %>   

	        <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
	        &nbsp
	      	<!-- <span id="cracker1-button"><em><%#= post.likes.count %> <%#= (post.likes.count) == 1 ? 'Like' : 'Likes'%></em></span>&nbsp&nbsp -->
			    <span class="index-btn">
				    <span id="cracker1-button"><%= link_to "show", post_path(post), class: "btn btn-info"%></span>&nbsp&nbsp
				    <span id="cracker1-button"><%= link_to "Edit", edit_post_path(post), method: 'get', class: "btn btn-info"%></span>
		    	</span>
		    </div>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/posts/show.html.erb
<!-- <h1>Posts show</h1> -->
<table class="table table-bordered text-center">
    
    <tbody id="<%= @post.id %>">
        <h3>Name : <%="#{@post.name}" %></h3><br>
        <%= image_tag @post.image,:size => "800x400" %>
        <br>

        <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <span id="cracker1-button"><%= link_to 'Unlike', post_like_path(@post, pre_like), method: :delete, class: "btn btn-outline-primary" %></span>
        <% else %>
            <span id="cracker1-button"><%= link_to 'Like', post_likes_path(@post), method: :post, class: "btn btn-outline-primary" %></span>
        <% end %>   

        <%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%>
    </tbody>
</table>
<div id="cracker1-button"><%= link_to "Back", posts_path, class: "btn btn-info"%></div>

                

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>